apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "{{ template "harbor.fullname" . }}-jobservice"
  labels:
    app: "{{ template "harbor.fullname" . }}-jobservice"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: "{{ template "harbor.fullname" . }}-jobservice"
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: "{{ .Release.Name }}"
        heritage: "{{ .Release.Service }}"
    spec:
      containers:
      - name: jobservice
        image: vmware/harbor-jobservice:v1.3.0
        env:
          - name: UI_SECRET
            valueFrom:
              secretKeyRef:
                name: "{{ template "harbor.fullname" . }}-ui"
                key: UI_SECRET
          - name: JOBSERVICE_SECRET
            valueFrom:
              secretKeyRef:
                name: "{{ template "harbor.fullname" . }}-jobservice"
                key: JOBSERVICE_SECRET
          - name: LOG_LEVEL
            value: debug
          - name: CONFIG_PATH
            value: /etc/jobservice/app.conf
          - name: GODEBUG
            value: netdns=cgo
          - name: ADMINSERVER_URL
            value: "http://{{ template "harbor.fullname" . }}-adminserver"            
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: jobservice-config
          mountPath: /etc/jobservice/app.conf
          subPath: app.conf
        - name: jobservice-secrets
          mountPath: /etc/jobservice/key
          subPath: key
        - name: job-logs
          mountPath: /var/log/jobs
      volumes:
      - name: jobservice-config
        configMap:
          name: "{{ template "harbor.fullname" . }}-jobservice"
      - name: jobservice-secrets
        secret:
          secretName: "{{ template "harbor.fullname" . }}-jobservice"
          items:
            - key: key
              path: key
      - name: job-logs
        emptyDir: {}
