apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
#     volume.beta.kubernetes.io/storage-class: default
  name: "{{ template "harbor.fullname" . }}-registry-data"
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
