{{ if .Values.clair.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: "{{ template "harbor.fullname" . }}-clair"
  name: "{{ template "harbor.fullname" . }}-clair"
spec:
  ports:
    - port: 6060
  selector:
    app: "{{ template "harbor.fullname" . }}-clair"
{{ end }}