{{ if .Values.clair.enabled }}
{{ if .Values.harbor.storage.persistent }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-class: <your-storage-class>
  name: {{ template "harbor.fullname" . }}-clair-pg-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
{{ end }}
{{ end }}