{{ if .Values.clair.enabled }}
apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: {{ template "harbor.fullname" . }}-clair-pg
  labels:
    app: {{ template "harbor.fullname" . }}-clair-pg
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"      
spec:
  serviceName: "{{ template "harbor.fullname" . }}-clair-pg"
  selector:
    matchLabels:
      app: "{{ template "harbor.fullname" . }}-clair-pg"
  template:
    metadata:
      name: {{ template "harbor.fullname" . }}-clair-pg
      labels:
        app: {{ template "harbor.fullname" . }}-clair-pg
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: "{{ .Release.Name }}"
        heritage: "{{ .Release.Service }}"          
    spec:
      containers:
      - name: postgres
        image: postgres:9.6.4
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "harbor.fullname" . }}-clair-pg-config
              key: POSTGRES_ROOT_PASSWORD
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 512Mi
        volumeMounts:
        - name: pgdata
          mountPath: /var/lib/postgresql
        ports:
        - containerPort: 5432
          name: postgres-port
          protocol: TCP
      volumes:
      - name: pgdata
        emptyDir: {}
#        persistentVolumeClaim:
#          claimName: {{ template "harbor.fullname" . }}-clair-pg-data
{{ end }}