{{ if .Values.clair.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "harbor.fullname" . }}-clair-pg-config
type: Opaque
data:
  POSTGRES_ROOT_PASSWORD: {{ .Values.clair.postgresRootPassword | b64enc | quote }}
{{ end }}