apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: "{{ template "harbor.fullname" . }}-adminserver"
  labels:
    app: "{{ template "harbor.fullname" . }}-adminserver"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: 1
  serviceName: "{{ template "harbor.fullname" . }}-adminserver"
  selector:
    matchLabels:
      app: "{{ template "harbor.fullname" . }}-adminserver"
  template:
    metadata:
      labels:
        app: "{{ template "harbor.fullname" . }}-adminserver"
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: "{{ .Release.Name }}"
        heritage: "{{ .Release.Service }}"  
    spec:
      containers:
      - name: adminserver
        image: "{{ .Values.adminserver.image.repository }}:{{ .Values.adminserver.image.tag }}"
        imagePullPolicy: "{{ .Values.adminserver.image.pullPolicy }}"
        envFrom:
        - configMapRef:
            name: "{{ template "harbor.fullname" . }}-adminserver"
        - secretRef:
            name: "{{ template "harbor.fullname" . }}-adminserver"
        env:
          - name: PORT
            value: "8080"
          - name: JSON_CFG_STORE_PATH
            value: /etc/adminserver/config.json
          - name: KEY_PATH
            value: /etc/adminserver/key
          - name: MYSQL_PWD
            valueFrom:
              secretKeyRef:
                name: "{{ template "harbor.fullname" . }}-adminserver"
                key: mysqlPass
          - name: UI_SECRET
            valueFrom:
              secretKeyRef:
                name: "{{ template "harbor.fullname" . }}-ui"
                key: UI_SECRET
          - name: JOBSERVICE_SECRET
            valueFrom:
              secretKeyRef:
                name: "{{ template "harbor.fullname" . }}-jobservice"
                key: JOBSERVICE_SECRET
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: adminserver-data
          mountPath: /data
        - name: adminserver-config
          mountPath: /etc/adminserver/app.conf
          subPath: app.conf
        - name: adminserver-key
          mountPath: /etc/adminserver/key
          subPath: key
      volumes:
      - name: adminserver-data
        emptyDir: {}
      - name: adminserver-config
        emptyDir: {}
      - name: adminserver-key
        secret:
          secretName: "{{ template "harbor.fullname" . }}-adminserver"
          items:
          - key: key
            path: key

