apiVersion: v1
kind: Secret
metadata:
  name: ui-secrets
type: Opaque
data:
  UI_SECRET: aE5IT21icEdEQTExeTZOcw==
  key: VTFLd1FCNzdVQXpOZUFRYQ==
  private_key.pem: <put here cert generated encoded in base64> 
